classdef WifiMapper < modem.Mapper
    %WIFIMAPPER defines a modulator for Wifi technology.
    %   This class inherits the main properties from "MAPPER" class and
    %   defines specific modulation mapper based on 802.11ac. It implements
    %   map and calculateLlr methods for wifi.
    %   This class uses modulations: BPSK, QPSK, 16QAM, 64QAM and 256QAM.
    %
    %
    %   Methods:
    %   Constructor
    %       Syntax: this = modem.WifiMapper( modulationOrder )
    %           Creates an instance of mapper class with the alphabets defined
    %           in Wifi standards.
    %
    %
    %   Author: Sergio Abreu (SA)
    %   Work Address: INDT Manaus
    %   E-mail: sergio.abreu>@indt.org.br
    %   History:
    %       v2.0 29 June 2015 (SA) - created
    %
    %   Copyright (c) 2015 INDT - Institute of Technology Development.
    %
    %   The program may be used and/or copied only with the written
    %   permission of INDT, or in accordance with the terms and conditions
    %   stipulated in the agreement/contract under which the program has been
    %   supplied.


    methods

        % constructor
        function this = WifiMapper( modulationOrder )

            % Define symbol alphabet for BPSK, QPSK, 16QAM, 64QAM.
            %  according to standard: Part 11-  Wireless LAN Medium Access Control
            % (MAC) and Physical Layer (PHY) Specifications, 2012. Section
            % 18.3.5.8. IEEE Std 802.11™-2012(Revision of IEEE Std
            % 802.11-2007)
            % and 256QAM according to standard Part 11: Wireless LAN Medium Access Control
            % (MAC) and Physical Layer (PHY) Specifications. Amendment 4: Enhancements for Very High
            %  Throughput for Operation in Bands below 6 GHz. Section
            %  22.3.10.9. IEEE Std 802.11ac™-2013 (Amendment to IEEE Std 802.11™-2012,
            %  as amended by IEEE Std 802.11ae™-2012, IEEE Std 802.11aa™-2012,
            %  and IEEE Std 802.11ad™-2012.

            % BPSK symbol alphabet, defined in Table 18-8
            % b1 = I; Q = 0;
            symbolAlphabet{1}   = [ -1; 1 ];

            % QPSK symbol alphabet, defined in Table 18-9
            % b1.b2 (I.Q): I = b1; Q = b2;
            symbolAlphabet{2}   = [ -1-1j; -1+1j; 1-1j; +1+1j]/sqrt(2);

            %16QAM symbol alphabet, defined in Table 18-10
            % b1b2.b3b4 (I.Q): I = b1b2; Q = b3b4;
            symbolAlphabet{4}   = [
                complex( -3, -3 ); ...
                complex( -3, -1 ); ...
                complex( -3,  3 ); ...
                complex( -3,  1 ); ...
                complex( -1, -3 ); ...
                complex( -1, -1 ); ...
                complex( -1,  3 ); ...
                complex( -1,  1 ); ...
                complex(  3, -3 ); ...
                complex(  3, -1 ); ...
                complex(  3,  3 ); ...
                complex(  3,  1 ); ...
                complex(  1, -3 ); ...
                complex(  1, -1 ); ...
                complex(  1,  3 ); ...
                complex(  1,  1 )] / sqrt(10);

            % 64QAM symbol alphabet, defined in Table 18-11
            % b1b2b3.b4b5b6 (I.Q): I = b1b2b3; Q = b4b5b6;
            symbolAlphabet{6}  =  [
                complex( -7, -7 ); ...
                complex( -7, -5 ); ...
                complex( -7, -1 ); ...
                complex( -7, -3 ); ...
                complex( -7,  7 ); ...
                complex( -7,  5 ); ...
                complex( -7,  1 ); ...
                complex( -7,  3 ); ...
                %
                complex( -5, -7 ); ...
                complex( -5, -5 ); ...
                complex( -5, -1 ); ...
                complex( -5, -3 ); ...
                complex( -5,  7 ); ...
                complex( -5,  5 ); ...
                complex( -5,  1 ); ...
                complex( -5,  3 ); ...
                %
                complex( -1, -7 ); ...
                complex( -1, -5 ); ...
                complex( -1, -1 ); ...
                complex( -1, -3 ); ...
                complex( -1,  7 ); ...
                complex( -1,  5 ); ...
                complex( -1,  1 ); ...
                complex( -1,  3 ); ...
                %
                complex( -3, -7 ); ...
                complex( -3, -5 ); ...
                complex( -3, -1 ); ...
                complex( -3, -3 ); ...
                complex( -3,  7 ); ...
                complex( -3,  5 ); ...
                complex( -3,  1 ); ...
                complex( -3,  3 ); ...
                %
                complex( 7,  -7 ); ...
                complex( 7,  -5 ); ...
                complex( 7,  -1 ); ...
                complex( 7,  -3 ); ...
                complex( 7,   7 ); ...
                complex( 7,   5 ); ...
                complex( 7,   1 ); ...
                complex( 7,   3 ); ...
                %
                complex( 5,  -7 ); ...
                complex( 5,  -5 ); ...
                complex( 5,  -1 ); ...
                complex( 5,  -3 ); ...
                complex( 5,   7 ); ...
                complex( 5,   5 ); ...
                complex( 5,   1 ); ...
                complex( 5,   3 ); ...
                %
                complex( 1,  -7 ); ...
                complex( 1,  -5 ); ...
                complex( 1,  -1 ); ...
                complex( 1,  -3 ); ...
                complex( 1,   7 ); ...
                complex( 1,   5 ); ...
                complex( 1,   1 ); ...
                complex( 1,   3 ); ...
                %
                complex( 3,  -7 ); ...
                complex( 3,  -5 ); ...
                complex( 3,  -1 ); ...
                complex( 3,  -3 ); ...
                complex( 3,   7 ); ...
                complex( 3,   5 ); ...
                complex( 3,   1 ); ...
                complex( 3,   3 ) ] / sqrt(42);

            % 256QAM symbol alphabet, defined in Section 22.3.10.9 of IEEE Std 802.11ac™-2013
            % b1b2b3b4.b5b6b7b8; (I.Q): I = b1b2b3b4; Q = b5b6b7b8;
            symbolAlphabet{8} = [
                complex( -15, -15 ); ...
                complex( -15, -13 ); ...
                complex( -15,  -9 ); ...
                complex( -15, -11 ); ...
                complex( -15,  -1 ); ...
                complex( -15,  -3 ); ...
                complex( -15,  -7 ); ...
                complex( -15,  -5 ); ...
                %
                complex( -15,  15 ); ...
                complex( -15,  13 ); ...
                complex( -15,   9 ); ...
                complex( -15,  11 ); ...
                complex( -15,   1 ); ...
                complex( -15,   3 ); ...
                complex( -15,   7 ); ...
                complex( -15,   5 ); ...
                %
                complex( -13, -15 ); ...
                complex( -13, -13 ); ...
                complex( -13,  -9 ); ...
                complex( -13, -11 ); ...
                complex( -13,  -1 ); ...
                complex( -13,  -3 ); ...
                complex( -13,  -7 ); ...
                complex( -13,  -5 ); ...
                %
                complex( -13,  15 ); ...
                complex( -13,  13 ); ...
                complex( -13,   9 ); ...
                complex( -13,  11 ); ...
                complex( -13,   1 ); ...
                complex( -13,   3 ); ...
                complex( -13,   7 ); ...
                complex( -13,   5 ); ...
                %
                complex( -9, -15 ); ...
                complex( -9, -13 ); ...
                complex( -9,  -9 ); ...
                complex( -9, -11 ); ...
                complex( -9,  -1 ); ...
                complex( -9,  -3 ); ...
                complex( -9,  -7 ); ...
                complex( -9,  -5 ); ...
                %
                complex( -9, 15  ); ...
                complex( -9, 13  ); ...
                complex( -9,  9  ); ...
                complex( -9, 11  ); ...
                complex( -9,  1  ); ...
                complex( -9,  3  ); ...
                complex( -9,  7  ); ...
                complex( -9,  5  ); ...
                %
                complex( -11, -15 ); ...
                complex( -11, -13 ); ...
                complex( -11,  -9 ); ...
                complex( -11, -11 ); ...
                complex( -11,  -1 ); ...
                complex( -11,  -3 ); ...
                complex( -11,  -7 ); ...
                complex( -11,  -5 ); ...
                %
                complex( -11, 15 ); ...
                complex( -11, 13 ); ...
                complex( -11,  9 ); ...
                complex( -11, 11 ); ...
                complex( -11,  1 ); ...
                complex( -11,  3 ); ...
                complex( -11,  7 ); ...
                complex( -11,  5 ); ...
                %
                complex( -1, -15 ); ...
                complex( -1, -13 ); ...
                complex( -1,  -9 ); ...
                complex( -1, -11 ); ...
                complex( -1,  -1 ); ...
                complex( -1,  -3 ); ...
                complex( -1,  -7 ); ...
                complex( -1,  -5 ); ...
                %
                complex( -1, 15 ); ...
                complex( -1, 13 ); ...
                complex( -1,  9 ); ...
                complex( -1, 11 ); ...
                complex( -1,  1 ); ...
                complex( -1,  3 ); ...
                complex( -1,  7 ); ...
                complex( -1,  5 ); ...
                %
                complex( -3, -15 ); ...
                complex( -3, -13 ); ...
                complex( -3,  -9 ); ...
                complex( -3, -11 ); ...
                complex( -3,  -1 ); ...
                complex( -3,  -3 ); ...
                complex( -3,  -7 ); ...
                complex( -3,  -5 ); ...
                %
                complex( -3, 15 ); ...
                complex( -3, 13 ); ...
                complex( -3,  9 ); ...
                complex( -3, 11 ); ...
                complex( -3,  1 ); ...
                complex( -3,  3 ); ...
                complex( -3,  7 ); ...
                complex( -3,  5 ); ...
                %
                complex( -7, -15 ); ...
                complex( -7, -13 ); ...
                complex( -7,  -9 ); ...
                complex( -7, -11 ); ...
                complex( -7,  -1 ); ...
                complex( -7,  -3 ); ...
                complex( -7,  -7 ); ...
                complex( -7,  -5 ); ...
                %
                complex( -7, 15 ); ...
                complex( -7, 13 ); ...
                complex( -7,  9 ); ...
                complex( -7, 11 ); ...
                complex( -7,  1 ); ...
                complex( -7,  3 ); ...
                complex( -7,  7 ); ...
                complex( -7,  5 ); ...
                %
                complex( -5, -15 ); ...
                complex( -5, -13 ); ...
                complex( -5,  -9 ); ...
                complex( -5, -11 ); ...
                complex( -5,  -1 ); ...
                complex( -5,  -3 ); ...
                complex( -5,  -7 ); ...
                complex( -5,  -5 ); ...
                %
                complex( -5, 15 ); ...
                complex( -5, 13 ); ...
                complex( -5,  9 ); ...
                complex( -5, 11 ); ...
                complex( -5,  1 ); ...
                complex( -5,  3 ); ...
                complex( -5,  7 ); ...
                complex( -5,  5 ); ...
                %
                complex( 15, -15 ); ...
                complex( 15, -13 ); ...
                complex( 15,  -9 ); ...
                complex( 15, -11 ); ...
                complex( 15,  -1 ); ...
                complex( 15,  -3 ); ...
                complex( 15,  -7 ); ...
                complex( 15,  -5 ); ...
                %
                complex( 15, 15 ); ...
                complex( 15, 13 ); ...
                complex( 15,  9 ); ...
                complex( 15, 11 ); ...
                complex( 15,  1 ); ...
                complex( 15,  3 ); ...
                complex( 15,  7 ); ...
                complex( 15,  5 ); ...
                %
                complex( 13, -15 ); ...
                complex( 13, -13 ); ...
                complex( 13,  -9 ); ...
                complex( 13, -11 ); ...
                complex( 13,  -1 ); ...
                complex( 13,  -3 ); ...
                complex( 13,  -7 ); ...
                complex( 13,  -5 ); ...
                %
                complex( 13, 15 ); ...
                complex( 13, 13 ); ...
                complex( 13,  9 ); ...
                complex( 13, 11 ); ...
                complex( 13,  1 ); ...
                complex( 13,  3 ); ...
                complex( 13,  7 ); ...
                complex( 13,  5 ); ...
                %
                complex( 9, -15 ); ...
                complex( 9, -13 ); ...
                complex( 9,  -9 ); ...
                complex( 9, -11 ); ...
                complex( 9,  -1 ); ...
                complex( 9,  -3 ); ...
                complex( 9,  -7 ); ...
                complex( 9,  -5 ); ...
                %
                complex( 9, 15 ); ...
                complex( 9, 13 ); ...
                complex( 9,  9 ); ...
                complex( 9, 11 ); ...
                complex( 9,  1 ); ...
                complex( 9,  3 ); ...
                complex( 9,  7 ); ...
                complex( 9,  5 ); ...
                %
                complex( 11, -15 ); ...
                complex( 11, -13 ); ...
                complex( 11,  -9 ); ...
                complex( 11, -11 ); ...
                complex( 11,  -1 ); ...
                complex( 11,  -3 ); ...
                complex( 11,  -7 ); ...
                complex( 11,  -5 ); ...
                %
                complex( 11, 15 ); ...
                complex( 11, 13 ); ...
                complex( 11,  9 ); ...
                complex( 11, 11 ); ...
                complex( 11,  1 ); ...
                complex( 11,  3 ); ...
                complex( 11,  7 ); ...
                complex( 11,  5 ); ...
                %
                complex( 1, -15 ); ...
                complex( 1, -13 ); ...
                complex( 1,  -9 ); ...
                complex( 1, -11 ); ...
                complex( 1,  -1 ); ...
                complex( 1,  -3 ); ...
                complex( 1,  -7 ); ...
                complex( 1,  -5 ); ...
                %
                complex( 1, 15 ); ...
                complex( 1, 13 ); ...
                complex( 1,  9 ); ...
                complex( 1, 11 ); ...
                complex( 1,  1 ); ...
                complex( 1,  3 ); ...
                complex( 1,  7 ); ...
                complex( 1,  5 ); ...
                %
                complex( 3, -15 ); ...
                complex( 3, -13 ); ...
                complex( 3,  -9 ); ...
                complex( 3, -11 ); ...
                complex( 3,  -1 ); ...
                complex( 3,  -3 ); ...
                complex( 3,  -7 ); ...
                complex( 3,  -5 ); ...
                %
                complex( 3, 15 ); ...
                complex( 3, 13 ); ...
                complex( 3,  9 ); ...
                complex( 3, 11 ); ...
                complex( 3,  1 ); ...
                complex( 3,  3 ); ...
                complex( 3,  7 ); ...
                complex( 3,  5 ); ...
                %
                complex( 7, -15 ); ...
                complex( 7, -13 ); ...
                complex( 7,  -9 ); ...
                complex( 7, -11 ); ...
                complex( 7,  -1 ); ...
                complex( 7,  -3 ); ...
                complex( 7,  -7 ); ...
                complex( 7,  -5 ); ...
                %
                complex( 7, 15 ); ...
                complex( 7, 13 ); ...
                complex( 7,  9 ); ...
                complex( 7, 11 ); ...
                complex( 7,  1 ); ...
                complex( 7,  3 ); ...
                complex( 7,  7 ); ...
                complex( 7,  5 ); ...
                %
                complex( 5, -15 ); ...
                complex( 5, -13 ); ...
                complex( 5,  -9 ); ...
                complex( 5, -11 ); ...
                complex( 5,  -1 ); ...
                complex( 5,  -3 ); ...
                complex( 5,  -7 ); ...
                complex( 5,  -5 ); ...
                %
                complex( 5, 15 ); ...
                complex( 5, 13 ); ...
                complex( 5,  9 ); ...
                complex( 5, 11 ); ...
                complex( 5,  1 ); ...
                complex( 5,  3 ); ...
                complex( 5,  7 ); ...
                complex( 5,  5 )] / sqrt(170);

            this@modem.Mapper( symbolAlphabet, modulationOrder )

        end

    end

end